version: "3.1"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: lDvEFVkVyVpHuCOK9To3
    # ports:
    #   - 5432:5432
    volumes:
      - ./dbdumps:/opt/dbdumps
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  ofbiz:
    build: ofbiz
    depends_on:
      - db
    ports:
      - 8443:8443
    # command: ["/ofbiz/gradlew", "loadAll"]
    # command: ["/ofbiz/gradlew", "ofbiz"]
